### ISSUE TITLE
How to extends django orm mixins

### ISSUE THREAD

**Issue by LeonardoGentile** [omab/python-social-auth#343]
I'm using django and I need some custom methods to work on the Django User model.
So for example I need a method to get the user by a specified field. 

So far I've understood I have to extends the `DjangoUserMixin` mixin in  `storage.django_orm ` but how? 

I mean I can subclass the `DjangoUserMixin` to write my custom methods but then how to tell PSA to use it instead of the default one?

**Comment by alfetopito** [comment]
Hi there.

@omab I'm doing exactly as you said, but it is not working.
Looking through the issues I found this one and since it is the same I opted to comment it here. If you think a new issue would be better just let me know.

Anyway, I'm doing my custom model and custom storage, but both models are being created by Django, generating a conflict due to the related name in the user ForeignKey.

Here's a stub code for reference:

```
# users.models.py

class CustomUserSocialAuth(AbstractUserSocialAuth):
    """Social Auth association model"""

    @classmethod
    def create_user(cls, *args, **kwargs):
         # my custom method here
         pass

    class Meta:
        """Meta data"""
        unique_together = ('provider', 'uid')
        db_table = 'social_auth_usersocialauth'


-----
# user.storages.py

from .models import CustomUserSocialAuth

class PreCreatedUserStorage(DjangoStorage):
    """
    This storage was created with the sole purpose of using our pre-created
    unclaimed user accounts rather than creating brand new user objects
    """
    user = CustomUserSocialAuth


-----
# settings.py

SOCIAL_AUTH_STORAGE = 'users.storages.PreCreatedUserStorage'
```

The error:

```
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
default.UserSocialAuth.user: (fields.E304) Reverse accessor for 'UserSocialAuth.user' clashes with reverse accessor for 'CustomUserSocialAuth.user'.
	HINT: Add or change a related_name argument to the definition for 'UserSocialAuth.user' or 'CustomUserSocialAuth.user'.
default.UserSocialAuth.user: (fields.E305) Reverse query name for 'UserSocialAuth.user' clashes with reverse query name for 'CustomUserSocialAuth.user'.
	HINT: Add or change a related_name argument to the definition for 'UserSocialAuth.user' or 'CustomUserSocialAuth.user'.
users.CustomUserSocialAuth.user: (fields.E304) Reverse accessor for 'CustomUserSocialAuth.user' clashes with reverse accessor for 'UserSocialAuth.user'.
	HINT: Add or change a related_name argument to the definition for 'CustomUserSocialAuth.user' or 'UserSocialAuth.user'.
users.CustomUserSocialAuth.user: (fields.E305) Reverse query name for 'CustomUserSocialAuth.user' clashes with reverse query name for 'UserSocialAuth.user'.
	HINT: Add or change a related_name argument to the definition for 'CustomUserSocialAuth.user' or 'UserSocialAuth.user'.
```

I believe that if I use a different related name it will pass the initial check, but maybe the reverse relationship is used by PSA down the road.

Is there a better alternative to use a custom User model?

What I wanted to solve by creating a custom user is simply to override the `create_user` method. Maybe I don't need a custom UserSocialAuth model.

Thoughts?

**Comment by alfetopito** [comment]
One alternative that just occurred to me is instead of a custom storage, I can modify the `social.pipepline.user.create_user` function (https://github.com/omab/python-social-auth/blob/master/social%2Fpipeline%2Fuser.py#L58) to do the creation my own way.

Might work, but I still feel like this isn't the right place to do it.
