### ISSUE TITLE
User model instance gets returned in Flask

### ISSUE THREAD

**Issue by flying-sheep** [omab/python-social-auth#461]
[actions.do_complete](https://github.com/omab/python-social-auth/blob/v0.2.1/social/actions.py#L46) does the following:

``` python
user_model = backend.strategy.storage.user.user_model()
if user and not isinstance(user, user_model):
    return user
```

unfortunately, user is an instance of `werkzeug.local.LocalProxy` in flask, so i get “redirected” to the user object, resulting in an error.

**Comment by moorchegue** [comment]
Stumbled into this as well. I'm not sure what's the right place to fix it, because I aint dig too deep into psa or werkzeug to figure out possible responsibilities.

However just by the looking on the condition @flying-sheep mentioned and possible returned value I get really confused. Shouldn't the condition at least be more specific if we expect something response-like to be returned?

On more practical side of things. Is there anything I can do on my app side to make this work for now instead of patching psa/werkzeug code? Is there a related ticket/issue on werkzeug/flask-login bug trackers? Any cooperation is happenning on on this?

**Comment by omab** [comment]
The example app was corrected on on how to get the user instance, the library doesn't support lazy-like objects internally and a real user instance must be provided to it.
