### ISSUE TITLE
django example

### ISSUE THREAD

**Issue by bemall** [omab/python-social-auth#504]
The project and application format for this Django example looks vastly different from how django 1.7 creates projects  and apps. Why is this the case ?

**Comment by DavidJFelix** [comment]
@bemall I think it's an issue of tree structure. The "app" is in the wrong subtree (at least according to conventional django). The way it's organized is:

- example
  - manage.py
  - example
    - app
      - models.py
      - ...
    - urls.py
    - settings.py
    - templates
        - ...
    - wsgi.py
    - ...

This format isn't really idiomatic, but really shouldn't startle django veterans. The templates folder is configured in settings.py and as long as urls.py and settings.py correctly import the app, it can really exist anywhere, including places out of the source tree. I've never really seen a case where you'd want to nest apps as done in here, but if you did, nesting them in the "main" app is probably the least unusual way... if that makes sense.

If you're contemplating nesting apps, I would urge you to instead keep it as one app and split up the files in the app into a directory. This will take some work, but will be much cleaner in the end. Apps are meant to be siblings in a project, not parents and children -- even if they may depend on each other. There are a number of changes that cause unexpected behavior with nested apps [Including this](https://code.djangoproject.com/ticket/23348). It's not a supported workflow, as far as I know. Apps can contain modules rather than files if they get too large and are at a size where you might want nested apps. Here is how I would expect to see the django example laid out, in idiomatic django:

- example
  - manage.py
  - templates
      - ...
  - app
    - models.py
    - ...
  - example
    - urls.py
    - settings.py
    - wsgi.py
    - ...

To do this, there would need to be a few pathing changes to urls.py and settings.py, but it should work with a direct copy and paste, otherwise. I don't know that it's a big enough deal to modify the example, however.

**Comment by omab** [comment]
The app was created a long time ago when things where different, I don't see the need to change it, but if a pull-request is presented I'll merge it.

@DavidJFelix, thanks for that extensive description!

**Comment by DavidJFelix** [comment]
@omab I agree. I don't think the cleanup would be worth the effort needed to regression test and ensure the app is wired up correctly. Like I said, django veterans should be able to figure it out and if it annoys somebody enough, they can do the PR.

**Comment by bemall** [comment]
Thank you for the feedback and understood!
