### ISSUE TITLE
get() returned more than one UserSocialAuth -- it returned 2!

### ISSUE THREAD

**Issue by CrimsonRay** [omab/python-social-auth#553]
I'm trying to implement Steam login into my project, and I get the error `get() returned more than one UserSocialAuth -- it returned 2!` when I try to do `user.social_auth.get(provider='steam')`. This seems to happen when someone has the same username—the rows in social_auth_usersocialauth are associated to the same auth.User. Attached an image to show what I mean:
![screen shot 2015-03-18 at 8 01 37 pm](https://cloud.githubusercontent.com/assets/10459349/6708411/f5a54cf0-cdaa-11e4-93f5-dc3774e8809b.png)

As a side note, is it a good idea to store the Steam name as username field in auth.User? Steam names can be changed and are not unique. I think it's better to just return something unique for the username field, like UID.

**Comment by CrimsonRay** [comment]
Anyone?

**Comment by omab** [comment]
The steam username is used as a base to the user username, if it's duplicated, then a extra hash will be added (so they are never repeated), also, if the user changes his username in steam, it won't change the username in your site (username is defined only once).

You are getting that error because you have two steam accounts associated to a single user, python-social-auth doesn't put any constraint to that, you can have several accounts from the same provider associated to a given user.

You should do ``user.social_auth.filter(provider='steam')[0]`` (or select one of them).

**Comment by CrimsonRay** [comment]
>  if it's duplicated, then a extra hash will be added (so they are never repeated)

That's the problem here, it doesn't seem to add an extra hash when there are collisions. I logged in using two different Steam accounts with the same username and this happened.

Anyway, I solved the problem by writing a custom pipeline to replace usernames with Steam UIDs, it's good enough for my needs.

Thanks!

**Comment by boxconnect** [comment]
Has this been solved?  I am facing the same issue. @CrimsonRay: Could you provide your pipeline code?
