### ISSUE TITLE
Since 0.2.3, a conflicting migration was added (django)

### ISSUE THREAD

**Issue by niwinz** [omab/python-social-auth#608]
Hi! I have updated to last version of python-social-auth (0.2.7) and I found that the previosly existing migration `0002_auto_20141123_1349` is not exists (seems it is replaced by `0002_add_related_name`).

But on my applications using python-social-auth have the previous migration already applied, that causes this situation:

```
$ python manage.py migrate -l
[...]
default
 [X] 0001_initial
 [ ] 0002_add_related_name
 [X] 0002_auto_20141123_1349
[...]
```

```
$ python manage.py migrate
CommandError: Conflicting migrations detected (0002_auto_20141123_1349, 0002_add_related_name in default).
To fix them run 'python manage.py makemigrations --merge'
```

Independently of the automatic recommendation of django for fix this issue, it seems a very wrong approach renaming or replacing migrations when you software is used by other people :(

What is the recommended way to handle this situation?

**Comment by omab** [comment]
I don't see an reference to a migration named ``0002_auto_20141123_1349`` in the whole repository history, are you sure that that migration wasn't generated in your project?

**Comment by niwibe** [comment]
I found that in very different environments, but I'm not sure about all them! I'm not start suspect about possible issue until I found it in three different environments and not all are controlled by me.  

I'll check it in any case! Thanks for notice me about that possibility because I do not considered it :S

**Comment by julianwachholz** [comment]
This is an automatic migration Django created because you use a custom user model.
Maybe this was a buggy handling of the swappable dependency in `0001_initial` in previous versions of Django, becaue I just noticed that I have a similar migration created in my `site-packages`.

I guess yours will looks similar to this:

    operations = [
        migrations.AlterField(
            model_name='usersocialauth',
            name='user',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='social_auth'),
        ),
    ]

I'm not yet sure how to properly handle this, as I also can't roll back this migration now..
