### ISSUE TITLE
Token creation date is not stored

### ISSUE THREAD

**Issue by webjunkie** [omab/python-social-auth#843]
I was just about to write some code that checks if an `access_token` is still valid, but it turns out python social auth doesn't have the creation date of the `access_token` anywhere and thus I cannot calculate with the `expires` in any way. Did I miss something? I cannot use the creation date of the user account or similar because the social auth might come later and of course the token might get refreshed and then the expiration is counting from that time on.

**Comment by webjunkie** [comment]
For the provider I'm implementing I now made it so that every time it gets an access token, the `expires_in` (from the response) is stored in seconds, and right away `expires` is calculated as timestamp and also stored in `extra_data`. I could extend this and provide a pull request so that the base class always stores it that way for all providers, unless the values are somehow already set.

As far as I can see, that would not affect current workings, because the library already checks if the value in `expires` is a timestamp or a number of seconds. It would furthermore bring it closer to the OAuth2 standard, where `expires_in` is defined (as seconds) whereas this library only relies on `expires` (with mixed content).

**Comment by tkajtoch** [comment]
Hello, webjunkie.

You are right - python-social-auth does not store the time of `access_token` generation. The problem is you cannot check if `access_token` is still active without making a request to a provider.

Note that any provider does not return the exact date of `access_token` expiration - this is because the provider's backends can invalidate, delete or simply lost valid access tokens and they will have to be regenerated for your app.

**Comment by webjunkie** [comment]
I cannot check if it is still 100% active, that's right. But what I can do, and this is important for tokens with short expiration times, is checking whether it is expired or not. If they expire quickly and I can just check that, it doesn't make sense always trying to do a request.

**Comment by omab** [comment]
`UserSocialAuth` instances have a `expiration_datetime()` method that will return a `timedelta()` with how many seconds will remain the validity of the access token, this depends on the value of `expires` in `extra_data`, which is not stored by default for every backend, just a few define the needed value in the `EXTRA_DATA` dict. Also, there are some cases where the provider will return a seconds-to-live instead of a timestamp, and this case is not very well supported yet since there's no created-at time to track it against of, but that can be easily workarounded with a custom pipeline that stores such time in the `extra_data` attribute.
