### ISSUE TITLE
Facebook appsecret_proof incorrectly comptued

### ISSUE THREAD

**Issue by ayushsood** [omab/python-social-auth#879]
Facebook auth responds with: `Invalid appsecret_proof provided in the API argument` Authentication works if `SOCIAL_AUTH_APPSECRET_PROOF` is set to `False`.

https://github.com/omab/python-social-auth/blob/master/social/backends/facebook.py#L50

**Comment by mohibhassan1990** [comment]
Agreed. Having the same issue. Thanks for the tip!

**Comment by hmilkovi** [comment]
+1

**Comment by ash6851** [comment]
+1

**Comment by jamesmcnamara** [comment]
+ 1

**Comment by Revocsid** [comment]
+1

**Comment by omab** [comment]
I can't reproduce this, `appsecret_proof` seems to be generated accordingly the rules in [facebook docs](https://developers.facebook.com/docs/graph-api/securing-requests), maybe this got fixed in the recent update to the backend.

I'm closing it, if still relevant, please open a ticket in [social-core](https://github.com/python-social-auth/social-core) component.

Thanks
